name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Bootstrap Lerna
        run: yarn lerna bootstrap

      - name: Run linter
        run: yarn lint

      - name: Build all packages
        run: yarn build

      - name: Run tests
        run: yarn test
