name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Bootstrap Lerna
        run: yarn run lerna bootstrap

      - name: Build all packages
        run: yarn run build

      - name: Run all tests
        run: yarn run test
