name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Restore node_modules from cache
      #   uses: actions/cache@master
      #   with:
      #     path: |
      #       node_modules
      #       */*/node_modules
      #     key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Bootstrap Lerna
        run: yarn run lerna bootstrap

      - name: Build all packages
        run: yarn run build:all

      - name: Run all tests
        run: yarn run test:all
